################################################################################
# Copyright (c) 2018 TESIS GmbH
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#  Frederic Chucholowski (TESIS GmbH) - initial implementation
###############################################################################

# ID of the detected object
int32 id
# longitudinal distance of the object to the sensor (sensor system)
float32 x
# lateral distance of the object to the sensor (sensor system)
float32 y
# radial velocity of the object relative to the sensor
float32 v_rad
# radial acceleration of the object relative to the sensor
float32 a_rad
